---
title       : Testing Slidify
subtitle    : A dumping ground where I test out new styles of Slidify
author      : Kevin
today       : " `r Sys.Date()` "
framework   : bootstrap3
highlighter : highlight.js 
hitheme     : github      
widgets     : []
layout      : deck3
mode        : selfcontained 
knit        : slidify::knit2slides
assets      : 
  css       : 
    - "assets/css/table-styles.css"
    - "assets/css/custom.css"
    - "assets/css/moving_sidebar.css"
    - "http://fonts.googleapis.com/css?family=Vollkorn"
    - "http://fonts.googleapis.com/css?family=Droid%20Sans%20Mono"
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE}
library(knitr)
opts_chunk$set(echo = T, 
               message = F, 
               warning = F, 
               cache = F, 
               tidy = F, 
               comment = "#>", 
               fig.align = "center", 
               fig.width = 8, 
               fig.height = 5, 
               digits = 3, 
               size = "small")
options(show.signif.stars = F, 
        digits = 3)
set.seed(99)
take_home <- 0
```

## Introduction

[Slidify](slidify.org) is an R package which makes it easy to generate cusomized HTML content from a simple RMarkdown file.  The sure can specify custom templates and 


This is where I test out new slidify layouts!

---
## An example plot

Using the `cars` data in R

```{r cars-plot}
plot(dist ~ speed, data = cars)
```

---
## An example table using `knitr`

```{r cars-table, results='asis'}
knitr::kable(head(cars), format = "markdown")
```

---
## Some example R output

```{r cars-lm}
fit1 <- lm(dist ~ speed, data = cars)
summary(fit1)
```

